name: Tests Socket
on: [push, pull_request]
jobs:
  tests:
    docker:
      - image: bitnami/rabbitmq:latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.13.0]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install -g npm@latest
        env:
          CI: true
        run: |
          npm install -g npm@latest
      # - name: npm ci
      #   env:
      #     CI: true
      #   run: |
      #     npm ci
      - name: npm install
        env:
          CI: true
        run: |
          npm install
      - name: .env and test
        env:
          CI: true
        run: |
          echo 'export PORT=8000' >> .env
          echo 'export ETH_NET_NAME=rinkeby' >> .env
          echo 'export INFURA_KEY=811fe4fa5c4b41cb9b92f9656aaeaa3b' >> .env
          echo 'export ENV=development' >> .env
          echo 'export CONFIRMATION_NEEDED=1' >> .env
          echo 'export PRIVATE_KEY=MIIBOgIBAAJBALLaXE1qt9my6cWkh9NGYr+mM/WLagt8AqObSNs9sNbL9da6qrYxuq57XUepaWWgyA81bZXOUy25wfkBpwwQmXsCAwEAAQJAT6hrtdtTGTXTYsC98f6GWr9movU9/PF1p3KxB1y5l2Cu0Zef2aGXsSc6+QaFRQXgs3KL9giUam4DknOdmfY9AQIhAOh7N0vocqKsu9N33RMNg4if/uzsJ0ysLH965mImxIaBAiEAxPJIHQpxVRPZ3bUWgZYesEWalA7MCpxMPppssXxuOfsCIQCwquojojpzSsbVddInp25chhGI5BEdX/3UxoWK8yEHgQIgFb9/cR2HGFMB2va1TogKSYLWKAVeSMmrrboVyJ+p+GMCIGmPcNLl+QdKxivLLYVLK8JRRTglt9fJpLFKqZDboTUQ' >> .env
          echo 'export PUBLIC_KEY=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALLaXE1qt9my6cWkh9NGYr+mM/WLagt8AqObSNs9sNbL9da6qrYxuq57XUepaWWgyA81bZXOUy25wfkBpwwQmXsCAwEAAQ==' >> .env
          echo 'export HEROKU_API_TOKEN=7c3a85a2-a80c-4ced-bcb9-97c0f18d3568' >> .env
          echo 'export HEROKU_API_BEARER_TOKEN=b39c70fe-d147-468f-93ac-73f70ed7c8ee' >> .env
          echo 'export MS_MASTER_URL=https://ms-master-dev.herokuapp.com' >> .env
          echo 'export MS_WITHDRAW_URL=https://sandbox-ms-withdraw.betprotocol.com' >> .env
          echo 'export GITHUB_LAYOUT_REPO=layout-1' >> .env
          echo 'export BITGO_ENTERPRISE_ID=5e2ee3674141b74006f37e0b0fdf6813' >> .env
          echo 'export BITGO_KEY=v2x9c8c188179741a91e4778ae69e76116a2ef3980dacb035737c0feb55b76367c1' >> .env
          echo 'export QUOTA_GUARD_URL=http://1uf1vgmue9ztet:3k1ajq0eev28rmx06uvrj2ox8t@eu-west-static-04.quotaguard.com:9293' >> .env
          echo 'export SENDINBLUE_API_KEY=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' >> .env
          echo 'export SENDINBLUE_EMAIL_TO=sandbox.betprotocol.com' >> .env
          echo 'export LIMIT=1' >> .env
          echo 'export RATE=100' >> .env
          echo 'export PANDA_SCORE_TOKEN=wYwfdN96aghYf05IrYKI3Lu54vtUBphAaX4wKp9Iq0W9VnBoGR0' >> .env
          echo 'export RABBIT_URL_QUEUE_BET=amqp://guest:guest@localhost/' >> .env
          echo 'export MONGO_CONNECTION_STRING=mongodb+srv://BetProtocolAdmin:wNmm4OmASXEp8UXi@cluster0.2gxjd.mongodb.net' >> .env
          echo 'export SOCKET_HOST=http://localhost:8000' >> .env
          echo 'export MS_ESPORT_URL=http://localhost:8000' >> .env
          source .env
          npm run test-socket